# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1474915460);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1474915580);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1475520832);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1474915340);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1474915220);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1474915700);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 71680);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1473708582);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1477947303841");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1477949080841");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1477947304274");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1477950904274");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 3378);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160728204513");
user_pref("browser.startup.homepage_override.mstone", "48.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 0);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20161003);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1473708644780");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 4360);
user_pref("datareporting.sessions.current.main", 152);
user_pref("datareporting.sessions.current.sessionRestored", 3418);
user_pref("datareporting.sessions.current.startTime", "1477947296353");
user_pref("datareporting.sessions.current.totalTime", 29);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.6", "{\"s\":1477940649332,\"a\":8,\"t\":53,\"c\":false,\"m\":161,\"fp\":4060,\"sr\":3660}");
user_pref("datareporting.sessions.prunedIndex", 5);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.000886");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"3.0.0\",\"type\":\"extension\",\"descriptor\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/loop@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"48.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"48.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:48.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1474915460);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "48.0");
user_pref("extensions.lastPlatformVersion", "48.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{e566aeb4-512e-4254-8427-6e56d386ad19}\",\"addons\":{\"e10srollout@mozilla.org\":{\"version\":\"1.3\"},\"firefox@getpocket.com\":{\"version\":\"1.0.4\"},\"loop@mozilla.org\":{\"version\":\"3.0.0\"}}}");
user_pref("extensions.xpiState", "{\"app-system-addons\":{\"e10srollout@mozilla.org\":{\"d\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3\",\"st\":1474915461000},\"firefox@getpocket.com\":{\"d\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1474915461000},\"loop@mozilla.org\":{\"d\":\"/mit/francisc/.mozilla/firefox/o54so3gm.default/features/{e566aeb4-512e-4254-8427-6e56d386ad19}/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"3.0.0\",\"st\":1474915461000}},\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":false,\"v\":\"1.0\",\"st\":1469742182000},\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":false,\"v\":\"1.4.3\",\"st\":1469742183000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":false,\"v\":\"1.0.4\",\"st\":1469742183000}},\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"48.0\",\"st\":1469742512000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"48.0\",\"st\":1469742182000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"48.0\",\"st\":1469742512000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160728204513");
user_pref("gecko.mstone", "48.0");
user_pref("idle.lastDailyNotification", 1477940756);
user_pref("loop.copy.ticket", 59);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1473708645);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160728204513");
user_pref("media.gmp-manager.lastCheck", 1477940713);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 48899);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1477947296);
user_pref("toolkit.telemetry.cachedClientID", "8bf76e44-19c2-4a91-a465-58c190da6276");
user_pref("toolkit.telemetry.previousBuildID", "20160728204513");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
